sudo: required

language: php

php:
  - '7.0'

services:
  - docker

before_install:
  - docker build -t rknol/test0 .
  - composer install

script:
  - ./bin/phpunit

after_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rknol/test0