sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t rknol/test0 .
  - composer install

script:
  - ./vendor/bin/phpunit
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push rknol/test0