sudo: required

language: php

php:
  - '7.0'

services:
  - docker

before_install:
  - composer install

script:
  - php vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit

after_script:
  - rm -rf ./var/cache/* vendor ./var/sessions/* ./var/logs/* .php_cs_cache
  - docker build -t rknol/test0 .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rknol/test0