services:
    app.repository.customer:
        class: AppBundle\Repository\CustomerRepository
        arguments:
          - "@database_connection"

    app.repository.transaction:
        class: AppBundle\Repository\TransactionRepository
        arguments:
          - "@database_connection"